### ISSUE TITLE
Add examples to docs

### ISSUE THREAD

**Issue by claviska** [shoelace-style/webawesome#112]
Feel free to add to this list if you find any examples missing or in need of some love.

```[tasklist]
### Tasks
- [x] Add `with-header` and `with-footer` examples to dialog
- [x] Add `with-header` and `with-footer` examples to drawer
- [x] Add `data-dialog="dismiss" example to dialog
- [x] Add `data-drawer="dismiss" example to drawer
```
