### ISSUE TITLE
Pre-alpha docs TODO

### ISSUE THREAD

**Issue by claviska** [shoelace-style/webawesome#131]
We're getting so close! I went through the docs and found some things we need to address before releasing this week.

## Homepage

- [x] @lindsaym-fa - I’d like to add a more explicit notice telling users this is an alpha version, things may break, etc. Perhaps this is a callout that links to a page with more information such as “what to expect”, how to report issues, etc.
- [x] @lindsaym-fa: Can we add a call to action under  “You put the awesome in Web Awesome” that links to the installation page?

## Sidebar
- [x] Remove experimental section from sidebar
- [x] Remove `<wa-page>` from sidebar
- [x] ~~Question: do we want to open up a blank repo for GitHub issues for now? Or should they file them under Shoelace with a special tag?~~
  - I have created a repo for this purpose here: https://github.com/shoelace-style/webawesome-alpha
- [x] Help and support should link to the new alpha repo for bugs/questions
- [x] ~~@lindsaym-fa - should we add a close button to the mobile sidebar?~~
  - This has been added for mobile views
- [x] @KonnorRogers - scroll position is lost when navigating pages

## Installation
- [x] Remove theming section (add relevant info to the themes page instead)
- [x] Remove traditional loader tab
- [x] Remove bundling section — “coming soon”
- [x] Remove npm section — “coming soon”
- [x] Remove “difference between CDN and npm” section
- [x] @claviska - update CDN section with Web Awesome CDN links

## Usage
- [x] Remove code completion section for now (since we don’t have an npm package to install locally)

## Themes
- [x] review and update Themes documentation
  - Can we still nest themes by adding `class="wa-theme-default-dark"` to arbitrary elements? If not, we should remove the “using multiple themes” section.

## Customizing
- [x] @lindsaym-fa - we probably don't want to show people how to reset the entire palette here. Should we ditch that whole section?

## Localization
- [x] @claviska - update CDN links

## Contributing
- [x] Remove “is an open source project” or at least make it clear that only part of the project is open source now.

## Theming / color
- [x] @lindsaym-fa - should we make the color swatches copy buttons that copy the respective design tokens?

## Theming / shadows
- [x] @lindsaym-fa - should the bottom “Shadows” example be moved up? It seems like these are the more important tokens plus they have the visuals. Then we can show the supporting tokens underneath with descriptions.

## Theming / transitions
- [x] ~~@lindsaym-fa - should we put the Duration example on top?~~
  - I swapped them since duration is probably more useful than easing for most people.

### Component pages
- [x] @lindsaym-fa - can we add a “notice a bug / need help” blurb to component template? We can link back to the page I proposed that the homepage blurb will link to.
- [x] @claviska - update importing URLs for new CDN

### Miscellaneous
- [x] @lindsaym-fa - should we add the “on this page” outline to Getting Started and Theming pages? (If so, we can easily do this by updating the front matter to use the new `page-outline` layout.)
- [x] @lindsaym-fa - we need to fix code block highlighting colors in dark mode.
- [x] @lindsaym-fa - can we make the code block backgrounds dark in both light/dark modes? (The light gray background is starting to feel archaic.)
- [x] @lindsaym-fa - is the legacy Shoelace theme ready or should we skip it for this release?
- [x] @lindsaym-fa - many of the component pages scroll horizontally on mobile due to API tables. Should we let them scroll horizontally or do you prefer another behavior?
- [x] @lindsaym-fa - some of the API tables are rendering with whitespace and overflow

### Changelog
- [x] Remove 2.0 changelog items and link back to the 2.0 on Shoelace/GitHub
- [x] @claviska - changelog review
- [x] @claviska - add 3.0 release message

### Build
- [x] Don't publish stylesheets (just `default.css`)
- [x] Don’t publish applied styles
- [x] Don’t publish `<wa-page>`
- [x] Don’t publish the following pages
  - [x] Theme builder
  - [x] Style guide
  - [x] Form validation styles
  - [x] Sandbox
- [x] Adjust `%NPMDIR%` and `%CDNDIR%`
- [x] CodePen links should open correct once the CDN is in place

**Comment by claviska** [comment]
FYI — because we're using applied styles and `<wa-page>` for the docs, I couldn't exclude them from the alpha build BUT I did remove the documentation for them. This is why having a backend with kits will be nice, because it will be so much easier to create these bundles. :sweat:

**Comment by lindsaym-fa** [comment]
> Can we still nest themes by adding class="wa-theme-default-dark" to arbitrary elements? If not, we should remove the “using multiple themes” section.

This should still be the case. However, it looks like this isn't working 100% for input elements. I'll remove this piece from the doc for now and tackle #136 to resolve this.

**Comment by lindsaym-fa** [comment]
>  should we make the color swatches copy buttons that copy the respective design tokens?

This is a great idea! I'm going to save this task for last since the others seem more essential. (I won't take any offense if someone else gets to this first!)

**Comment by lindsaym-fa** [comment]
> is the legacy Shoelace theme ready or should we skip it for this release?

We'll skip it for now. I created #137 to finish it up.

**Comment by lindsaym-fa** [comment]
re:

>  should we make the color swatches copy buttons that copy the respective design tokens?

and

> can we add a “notice a bug / need help” blurb to component template? We can link back to the page I proposed that the homepage blurb will link to.

I created #139 and #140.
