### ISSUE TITLE
[Meta] Add styles for more native elements

### ISSUE THREAD

**Issue by claviska** [shoelace-style/webawesome#217]
When using Applied Styles, users should be able to use `<input>`, `<select>`, and other native form controls with Web Awesome styles without actually using the components.

- [x] https://github.com/shoelace-style/webawesome/issues/320
- [x] https://github.com/shoelace-style/webawesome/issues/321
- [x] https://github.com/shoelace-style/webawesome/issues/322
- [x] https://github.com/shoelace-style/webawesome/issues/323
- [x] https://github.com/shoelace-style/webawesome/issues/324
- [x] https://github.com/shoelace-style/webawesome/issues/326
- [x] https://github.com/shoelace-style/webawesome/issues/327
- [x] https://github.com/shoelace-style/webawesome/issues/328
 
 Lower priority:

- [x] https://github.com/shoelace-style/webawesome/issues/325
- [x] https://github.com/shoelace-style/webawesome/issues/329

Projected release: December 19, 2024

**Comment by claviska** [comment]
FYI — the native date/time picker icons can be tricky so let me know if you get stuck on them. (Firefox is especially picky about this.) Basically the best option these days seems to be using a background image + data URI with a custom SVG.

**Comment by LeaVerou** [comment]
I think `<input type=range>` is a big one too because it's so annoying to style.

IMO this issue is one of the most high priority items. 

`<details>` and `<dialog>` would also be useful, though lower priority.

**Comment by claviska** [comment]
We have styles for details, but not dialog. Good call.

**Comment by LeaVerou** [comment]
> We have styles for details, but not dialog. Good call.

Should we track them all here or did you intend this to be just for form elements?
Also, do you agree on range?

**Comment by claviska** [comment]
Yeah just track anything missing in applied styles here.

**Comment by LeaVerou** [comment]
Closing this since all of these are now done.
